src/core/Component.ts, src/core/ManagedObject.ts, src/ui/UIListCellAdapter.ts, src/ui/UIListController.ts
Mostly an overhaul of the Component class observer to allow preset active components to omit all but a few bindings.
=> Fix: parent bindings

src/ui/UIComponent.ts, src/ui/containers/UIContainer.ts, src/ui/controls/UIButton.ts, src/ui/controls/UIControl.ts
Now able to bind `navigateTo`. Actual navigation is handled at platform level instead to deal with cmd-click etc.
Breaking change IF not accompanied by `typescene-webapp` update -- must introduce update there first and start locking dependency to minor version.
=> Feature: better links

src/core/Component.ts, src/core/ManagedObject.ts, src/ui/UIListCellAdapter.ts, src/ui/UIListController.ts
Support for non-managed object values in bound list `items` property, able to bind to `"value"` in list cell adapter
=> Feature: better lists

JSX/index.d.ts, JSX/index.js, JSX/src/index.ts, JSX/src/tsconfig.json
Make `typescene/JSX` also export everything from `typescene` so there is no need for two import lines in JSX files.
=> Improve JSX module output

src/ui/UIFormContextController.ts, src/ui/containers/UIForm.ts, src/ui/controls/UITextField.ts, src/ui/controls/UIToggle.ts
Input controls rely on observing `form` for changes but the FormContextChange event is not a change event; now observing events properly.
=> Fix: observe form context change events

src/app/ViewActivity.ts
When the Application renderContext changes, the current (stored) renderCallback in ViewActivity is no longer valid, and a new one should be retrieved. This happens e.g. when the browser app is unmounted from one element and mounted to another.
=> Fix: Refresh ViewActivity render callback when render context changes

src/core/ManagedObject.ts, src/core/ManagedReference.ts, src/core/observe.ts, test/cases/core/02 ManagedList.ts
Added use of string as second property to observe() function; now it's possible to use it as a decorator for a static class-type property. This enables access to private properties from observer classes.
=> Allow use of @observe as a static property decorator

src/core/ManagedService.ts
This adds parameters to the `service` function, which allows it to be used as a non-decorator. This is a lot more intuitive for plain JS use:
`service("App.FooBar", MyActivity, "svc")`
instead of
`service("App.FooBar")(MyActivity.prototype, "svc")`
=> Allow use of service decorator as a function

src/core/Component.ts, src/core/ManagedObject.ts, src/core/observe.ts, test/TestCase.ts, test/cases/core/01 ManagedObject.ts, test/cases/core/01a observe.ts, test/cases/core/02 ManagedList.ts, test/cases/core/03 ManagedRecord.ts, test/run.js
* Make `observe` and `compose` functions more consistent so that they are a better alternative for JS and not just decorators.
* Add more tests for observers (and update the test tooling a bit)
=> Streamline compose and observe functions

src/app/ViewComponent.ts, src/core/Component.ts, src/ui/UIComponent.ts, src/ui/UIListCellAdapter.ts, src/ui/UIListController.ts, src/ui/UIMenu.ts, src/ui/UIModalController.ts, src/ui/UIRenderableController.ts, src/ui/UISelectionController.ts, src/ui/containers/UIContainer.ts
* Don't just propagate `UIComponentEvent` in UI components, but _all_ `ComponentEvent`s.
* Turn `UIListCellAdapterEvent` into a `ComponentEvent`.
=> Fix UIListCellAdapterEvent propagation

src/ui/UIFormContext.ts
There was an issue in `UIFormContext.set()` where a change event was emitted even if the value had not changed.
=> Fix issue with too many change events in form context

src/core/Binding.ts, src/core/Component.ts
There was an issue whereby:
1. A managed list was bound, which was a child list of another object
2. The original property changed to undefined
3. The binding cleared all the items from the bound list, destroying the items in the list
The 'clear' feature exists to clear lists that were automatically populated using array values; however this should obviously not apply if the ManagedList instance was bound directly.
Fixed now.
=> Fix issue: bound lists are cleared when binding becomes undefined

src/core/Component.ts, src/core/ManagedList.ts
There was an issue especially with buttons, where components were unbound and then bound again, but multiple properties are bound to the exact same binding. This leads to an issue "Cannot insert object that is already in this list" because the binding would be bound twice within the same update.
To be merged and released asap.
=> Fix issue where two properties are bound to the same binding

README.md
The additional slash at the end leads to a 404 page.
=> Fix doc URL

src/app/AppActivityList.ts, src/app/Application.ts
Quick change that makes it easier to write apps with a single activity, or multiple activities that do not use URL activation.
If none of the activities passed to `Application.with(...)` or `.run(...)` have a `path` property set, then all given activities are activated as soon as the Application itself is activated.
=> Activate app activities if none have paths

src/core/I18nService.ts, src/core/format.ts
This contains 3 changes:
- Add option for pluralizer to take numeric value from any parameter, not just the first one.
- Add non-standard `%n` formatting specifier for 'number' format which is like `%g` but never formats as exponential.
- Fix for `%f` and `%g` formatters in line with C-style `sprintf`
=> Fix strf formatting and i18n

.gitignore, package.json, src/app/AppComponent.ts, src/app/Application.ts, src/app/ViewActivity.ts, src/core/Binding.ts, src/ui/UIRenderContext.ts, src/ui/UITheme.ts, src/ui/controllers/UIListController.ts, src/ui/controllers/UIStyleController.ts
Gathering changes here for pushing to v3.1 release.
- Build targets for ES6 and ES8 as separate folders, so that they can be used with e.g. Webpack, or a specific `.min.js` file when targeting modern browsers. These include native classes, and native async/await, respectively.
- Binding improvements, for and/or methods and also new then/else methods; I found these useful to bind styles directly, rather than having to rely on `UIStyleController` (which also has a fix in this release)
- Theme/style improvements
- A new 'viewport context' that is bound from the rendering context, to support responsive/adaptive design scenarios just using bindings (e.g. `bind("viewportContext.narrow")`)
- A new 'book end' component that can be added as the last parameter to `UIListController`, which can …
=> Cleanup and features for v3.1

src/core/Component.ts
Forgot to add `inner` property to new action events from the event handler that is created for preset components.
=> Fix: add inner event to action event

src/core/I18nService.ts, src/core/format.ts
The 'or' filter was confusing, because it doesn't do the same as bind(...).or(...) which expects another **binding**, not a plain value. It's in fact the same as bind(...).else(...), so renaming this 'else' as well.
Leaving 'or' in the code as well for backwards compatibility but this is quasi-deprecated now since it's no longer mentioned in the docs.
=> Rename bind()/strf() filter `or` to `else`

src/app/AppActivity.ts, src/app/Application.ts, src/app/ViewComponent.ts, src/core/Binding.ts, src/core/Component.ts, src/core/ManagedEvent.ts, src/core/ManagedObject.ts, src/core/ManagedRecord.ts, src/core/observe.ts, src/ui/UIMenu.ts, src/ui/UIRenderableController.ts, src/ui/controllers/UIModalController.ts, test/cases/01 core/05 Component.ts
Add decorator that is the equivalent of both `managedChild` and `presetBoundComponent`, to make it easier to add child components to Component classes, without having to use a preset function.
See tests for examples.
=> Add component decorator

src/app/AppActivationContext.ts, src/app/AppActivity.ts, src/app/Application.ts, src/ui/controls/UIButton.ts
This PR makes path-based navigation more flexible and robust.
Buttons with `navigateTo` properties no longer immediately navigate to a link, but instead emit a 'Navigate' event. This event is handled by `AppActivity`, which in turns calls `Application.navigate()`. This makes it possible to override the navigation behavior.
Also, `Application.navigate()` now accepts a 'mode' object which makes it possible to a) go back first, and/or b) replace the current path instead of always 'pushing' to the browser history.
All of this is useful for apps that use hierarchical, flat, or master-detail navigation: cases where you want to use path-based navigation (either URL hashes or History API) but don't just want to introduce new history states and pop them off a stack.
=> Improve navigation using events and modes

src/app/AppActivity.ts, src/app/ViewActivity.ts, src/ui/UIMenu.ts, src/ui/controllers/UIListController.ts, src/ui/controllers/UISelectionController.ts
This PR fixes return types of some handler functions so that it’s easier to override them without resorting to ‘any’.
=> Fix return types for handler methods

src/app/AppException.ts
Adding a method to create a bunch of AppException types in one go, given an object that maps codes to I18nStrings (strf calls).
Example:
```ts
const ERR = AppException.group({
NotLoggedIn: strf("Not logged in"),
TooLarge: strf("The number %n is too large")
});
throw new ERR.NotLoggedIn();
throw new ERR.TooLarge(41);
```
=> Add `AppException.group()` method

src/ui/controls/UIButton.ts, src/ui/controls/UIControl.ts, src/ui/controls/UIImage.ts, src/ui/controls/UILabel.ts, src/ui/controls/UISpacer.ts, src/ui/controls/UIToggle.ts
Changing the type of `UIControl.shrinkwrap` to `boolean | "auto"` where the 'auto' value should NOT override `UIControl.dimensions.grow` at all. Previously there was no way to achieve this and the control always ended up with a CSS override for `flex-grow` to change the value from the applied style.
Now it's possible to set the grow/shrink values properly in the style, as long as `shrinkwrap` is set to 'auto'.
=> Add auto value to shrinkwrap property

src/app/ViewActivity.ts, src/ui/UIRenderContext.ts, src/ui/controllers/UIModalController.ts
This mostly resolves some confusion where 'modal' and 'dialog' were used interchangeably. Now, 'dialog' is an extension of 'modal'. Modal views are intended to cover the entire page (except margins) and Dialog views are intended to be dimensioned and (vertically) positioned.
- Added `UIRenderPlacement.MODAL` value
- `DialogViewActivity` now extends a new class `ModalViewActivity`
- Added `ViewActivity.showModalAsync` which works like `showDialogAsync` but for generic modal views.
=> Add modal view placement and modal view activity
